CREATE OR REPLACE PROCEDURE add_poke(V_NOME VARCHAR(20), V_REG VARCHAR(20), V_TIPO VARCHAR(20), 
									 V_JOGO VARCHAR(20), V_ALTURA NUMERIC(5,2), V_PESO NUMERIC(5,2),V_ATK INTEGER, 
									V_DEF INTEGER, V_HP INTEGER, V_SP_ATK INTEGER, V_SP_DEF INTEGER, V_SPEED INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO Pokemon (NOME, ALTURA, PESO) VALUES (V_NOME, V_ALTURA, V_PESO);
	INSERT INTO INFO (POKE_ID, REG, TIPO, JOGO) VALUES ((SELECT currval(pg_get_serial_sequence('pokemon','id'))), V_REG, V_TIPO, V_JOGO);
	INSERT INTO STATUS (POKE_ID, ATK, DEF, HP, SP_ATK, SP_DEF, SPEED) VALUES ((SELECT currval(pg_get_serial_sequence('pokemon','id'))),
																			 V_ATK, V_DEF, V_HP, V_SP_ATK, V_SP_DEF, V_SPEED);
	COMMIT;
END;$$

CALL add_poke ('Bulbassauro', 'kanto', 'Grama', 'Vermelho', 0.7, 6.9, 49, 49, 45, 65, 65, 45);
CALL add_poke ('Ivysaur', 'kanto', 'Grama', 'Vermelho', 1.0, 13.0, 62, 63, 60, 80, 80, 60);
CALL add_poke ('Venusaur', 'kanto', 'Grama', 'Vermelho', 2.0, 10.0, 82, 83, 80, 100, 100, 80);

/*SELECT setval('Pokemon_id_seq', (SELECT MAX(id) FROM Pokemon));*/





CREATE OR REPLACE PROCEDURE upd_poke(V_ID INTEGER, V_NOME VARCHAR(20), V_REG VARCHAR(20), V_TIPO VARCHAR(20), 
									 V_JOGO VARCHAR(20), V_ALTURA NUMERIC(5,2), V_PESO NUMERIC(5,2), V_ATK INTEGER,
									 V_DEF INTEGER, V_HP INTEGER, V_SP_ATK INTEGER, V_SP_DEF INTEGER, V_SPEED INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
	UPDATE Pokemon set NOME = V_NOME, ALTURA = V_ALTURA, PESO = V_PESO WHERE ID = V_ID;
	UPDATE INFO SET REG = V_REG, TIPO = V_TIPO, JOGO = V_JOGO WHERE POKE_ID = V_ID;
	UPDATE STATUS SET ATK = V_ATK, DEF = V_DEF, HP = V_HP, SP_ATK = V_SP_ATK, SP_DEF = V_SP_DEF, SPEED = V_SPEED WHERE POKE_ID = V_ID;
	
	COMMIT;
END;$$

CALL upd_poke (3, 'Venusaur', 'kanto', 'Grama', 'Vermelho', 2.0, 100.0, 82, 83, 80, 100, 100, 80);




CREATE OR REPLACE PROCEDURE del_poke(V_ID INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
	DELETE FROM INFO WHERE POKE_ID = V_ID;
	DELETE FROM STATUS WHERE POKE_ID = V_ID;
	DELETE FROM Pokemon WHERE ID = V_ID;
	
	COMMIT;
END;$$

CALL del_poke ();
	
	
SELECT * FROM Pokemon P, INFO I, STATUS S WHERE P.id = I.poke_id AND P.id = S.poke_id;
	